In [7]:
import control
import numpy as np


RE = 6378 # km
ROrb = 300 # km
r0 = RE + ROrb
mu = 398600


A = np.array([[           0, 1, 0,                0],
                [3*mu/(r0**3), 0, 0, 2*np.sqrt(mu/r0)],
                [ 0, 0, 0, 1],
                [0, -2*np.sqrt(mu/r0**5), 0, 0 ]])

B = np.array([[0,0],
                [1,0],
                [0,0],
                [0,1/r0]])

C = np.array([[1,0,0,0],[0,0,1,0]])

D = np.zeros([2,2])

AaugOL = np.block([[A, np.zeros([4,2])],[-C, np.zeros([2,2])]])
BaugOL = np.block([[B],[np.zeros([2,2])]])
CaugOL = np.block([C, np.zeros([2,2])])
DaugOL = np.zeros([2,2])

lambda_aug = np.linalg.eig(AaugOL).eigenvalues
V_aug = np.linalg.eig(AaugOL).eigenvectors

for i in range(6):
    lambda_ = lambda_aug[i]
    v = V_aug[:,i]
    r = np.linalg.matrix_rank(np.block([[lambda_*np.eye(6) - AaugOL],[CaugOL]]))
    
    #if r < 6:
        #print(f"{lambda_} is unobservable, eigenvector: {v}")

sys = control.StateSpace(AaugOL,BaugOL,CaugOL,DaugOL)
Wo = control.obsv(AaugOL,CaugOL)
Q,R = np.linalg.qr(np.transpose(Wo))

print(Q)

[[ 1.  0.  0.  0.  0.  0.]
 [-0.  0. -1.  0.  0.  0.]
 [-0. -1.  0.  0.  0.  0.]
 [-0. -0. -0.  1.  0.  0.]
 [-0. -0. -0. -0.  1.  0.]
 [-0. -0. -0. -0. -0.  1.]]
