In [2]:
import numpy as np
import scipy as sci
import control

In [3]:
## Define SS

RE = 6378 # km
ROrb = 300 # km
r0 = RE + ROrb
mu = 398600


A = np.array([[           0, 1, 0,                0],
                [3*mu/(r0**3), 0, 0, 2*np.sqrt(mu/r0)],
                [ 0, 0, 0, 1],
                [0, -2*np.sqrt(mu/r0**5), 0, 0 ]])

B = np.array([[0,0],
                [1,0],
                [0,0],
                [0,1/r0]])

C = np.array([[1,0,0,0],[0,0,1,0]])

D = np.zeros([2,2])

In [7]:
## Open loop poles

Evals, V = np.linalg.eig(A)

print(f"Open loop poles: \n l_1 = {Evals[0]} \n l_2 = {Evals[1]} \n l_3 = {Evals[2]} \n l_4 = {Evals[3]}")

Open loop poles: 
 l_1 = 0j 
 l_2 = 0.0011569085351242233j 
 l_3 = -0.0011569085351242233j 
 l_4 = 0j


In [9]:
## Controllability Matrix

P = control.ctrb(A,B)
print(np.linalg.matrix_rank(P))
print(f"P = {P}")
O = control.obsv(A,C)
print(f"O = {O}")
print(np.linalg.matrix_rank(O))


4
P = [[ 0.00000000e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00
   0.00000000e+00  2.31381707e-03 -1.33843736e-06  0.00000000e+00]
 [ 1.00000000e+00  0.00000000e+00  0.00000000e+00  2.31381707e-03
  -1.33843736e-06  0.00000000e+00  0.00000000e+00 -3.09689921e-09]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.49745433e-04
  -3.46483539e-07  0.00000000e+00  0.00000000e+00 -8.01699526e-10]
 [ 0.00000000e+00  1.49745433e-04 -3.46483539e-07  0.00000000e+00
   0.00000000e+00 -8.01699526e-10  4.63746512e-13  0.00000000e+00]]
O = [[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]
 [ 4.01531208e-06  0.00000000e+00  0.00000000e+00  1.54516704e+01]
 [ 0.00000000e+00 -3.46483539e-07  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -1.33843736e-06  0.00000000e+00  0.00